### ISSUE TITLE
cannot register my node

### ISSUE THREAD

**Issue by produnis** [jaywink/the-federation.info#119]
Hi there, I registered my pod at https://the-federation.info/register/friendica.produnis.de   but my pod still is not in the statistics...
It states to take "a few seconds", but after 10 hours I am still missing in the list....

**Comment by jaywink** [comment]
The reason is that your node is returning an 404 for the NodeInfo document that should exist: https://friendica.produnis.de/nodeinfo/1.0

The route is correctly listed here though: https://friendica.produnis.de/.well-known/nodeinfo

This sounds like a bug in Friendica since it clearly lists the nodeinfo route in the well-known document, but accessing it returns 404.

This might solve the issue though: https://github.com/friendica/friendica/issues/3855 - though still it sounds odd that it would list the route but not produce it. Maybe might make sense to raise that with friendica developers even if the setting solves this case, since this is not the first time I've seen this 👍 

Hope this helps, closing from this side as the document is clearly 404'ing and we can't add a node that doesn't expose information. Let me know if there is still a problem after getting a working nodeinfo document up.

**Comment by produnis** [comment]
thank you! setting "publish server information" in adim/settings seems to solve the problem...
