### ISSUE TITLE
BlaBlanet Social Network

### ISSUE THREAD

**Issue by royalterra** [jaywink/the-federation.info#58]
Hi front the moment Blablanet is a fork of Hubzilla with other features in advance development and we open source code in Github.

I will like to ask to be change the Icon in the Federation Info. Our Nodes are public us network BLA_BLANET and Software name sitename BlaBlaNet

The icons can be found in the Github repository or in 
https://blablanet.com/images/bb-16.png
https://blablanet.com/images/bb-32.png
https://blablanet.com/images/bb-64.png
https://blablanet.com/images/bb-128.png

Is important for us start making difference is two separate project. I will appreciate some help for resolve this issue

**Comment by jaywink** [comment]
There is a redesign of the site going on at the moment. You can follow the [new branch here](https://github.com/jaywink/the-federation.info/tree/redesign), also it is live as a dev site [here](https://dev.the-federation.info/).

The plan is to feature the most used software stacks, in the end most likely just diaspora, friendica and hubzilla (since redmatrix is just an old name). Everything else, basically automatically based on the `software` key in the statistics.json/NodeInfo, could be listed as additional software stacks utilizing the Diaspora protocol. This would also add BlaBlanet there as an individual entity.

We should probably suggest projects add their branding icons to the NodeInfo metainfo for example, so that this site can parse them from there.

If some project grows, we can consider highlighting it. Unfortunately we can't separately maintain all forks in the site manually unless they gain serious adoption as an independent software stack.

Thanks for logging this, I'll leave it open so to remember to handle the case of other software stacks.

**Comment by jaywink** [comment]
Actually there is #38 already as an older issue, so I'll close this here, thanks!
