### ISSUE TITLE
Cleaning time

### ISSUE THREAD

**Issue by Flaburgan** [jaywink/the-federation.info#96]
We should probably take some time to clean the code once https://github.com/jaywink/the-federation.info/issues/43 is closed (with code pushed to prod).

- [x] Remove unused vendors (files + includes in html) (hubinfo, bitcoin...)
- [x] Fix indentation
- [x] Moar data cleaning (kill those peaks!)
- [x] To complete...

**Comment by jaywink** [comment]
> Moar data cleaning (kill those peaks!)

Peaks cleaned! There was a bug with copying previous day statistics on a failure. It didn't check if the copy had happened. Some old hubzilla nodes did ~40 registers in the middle of the night and then all the requests failed, creating many dupe stats rows for the same day. Weird, was tricky to hunt down :D

Also, code indentation was done also some days ago. I'll close this issue since the only remaining issue would be "to complete" :)
